const properties = [
    {
        id: 1,
        title: "駅近デザイナーズマンション",
        price: 95000,
        type: "マンション",
        location: "東京都渋谷区神南1丁目",
        rooms: "1LDK",
        size: 35.5,
        station: "渋谷駅",
        walkTime: 5,
        image: "/api/placeholder/400/300",
        features: ["オートロック", "宅配ボックス", "バストイレ別"],
        description: "渋谷駅から徒歩5分、充実した設備のデザイナーズマンション"
    },
    {
        id: 2,
        title: "緑豊かな閑静な住宅街のアパート",
        price: 83000,
        type: "アパート",
        location: "東京都世田谷区若林",
        rooms: "2K",
        size: 40.2,
        station: "三軒茶屋駅",
        walkTime: 8,
        image: "/api/placeholder/400/300",
        features: ["2階角部屋", "日当たり良好", "バストイレ別"],
        description: "閑静な住宅街、買い物便利な好立地物件"
    },
    {
        id: 3,
        title: "新築タワーマンション",
        price: 120000,
        type: "マンション",
        location: "東京都中央区晴海",
        rooms: "1LDK",
        size: 45.0,
        station: "勝どき駅",
        walkTime: 10,
        image: "/api/placeholder/400/300",
        features: ["新築", "デザイナーズ", "ペット可"],
        description: "最上級の設備が整った新築タワーマンション"
    },
    {
        id: 4,
        title: "リノベーション済み古民家",
        price: 78000,
        type: "一戸建て",
        location: "東京都杉並区高円寺北",
        rooms: "2DK",
        size: 50.0,
        station: "高円寺駅",
        walkTime: 12,
        image: "/api/placeholder/400/300",
        features: ["リノベーション済", "庭付き", "駐輪場有"],
        description: "伝統的な佇まいを残しつつ現代的な設備を備えた物件"
    },
    {
        id: 5,
        title: "都心の便利な立地のコンパクトマンション",
        price: 92000,
        type: "マンション",
        location: "東京都新宿区北新宿",
        rooms: "1K",
        size: 25.5,
        station: "新宿駅",
        walkTime: 15,
        image: "/api/placeholder/400/300",
        features: ["システムキッチン", "エアコン付", "光インターネット"],
        description: "新宿駅徒歩圏内、単身者向けの使いやすい間取り"
    },
    {
        id: 6,
        title: "リバーサイドテラス",
        price: 135000,
        type: "マンション",
        location: "東京都江東区豊洲",
        rooms: "2LDK",
        size: 55.0,
        station: "豊洲駅",
        walkTime: 7,
        image: "/api/placeholder/400/300",
        features: ["河川敷近く", "24時間セキュリティ", "駐車場有"],
        description: "水辺の景色を楽しめる高級マンション"
    },
    {
        id: 7,
        title: "下町情緒あふれるアパート",
        price: 68000,
        type: "アパート",
        location: "東京都台東区浅草",
        rooms: "1DK",
        size: 32.0,
        station: "浅草駅",
        walkTime: 6,
        image: "/api/placeholder/400/300",
        features: ["商店街近く", "エアコン付", "フローリング"],
        description: "浅草の街並みを感じられる、味のある物件"
    },
    {
        id: 8,
        title: "スカイビューレジデンス",
        price: 145000,
        type: "マンション",
        location: "東京都港区芝浦",
        rooms: "2LDK",
        size: 60.0,
        station: "田町駅",
        walkTime: 9,
        image: "/api/placeholder/400/300",
        features: ["高層階", "眺望良好", "防音設計"],
        description: "東京湾を一望できる高層マンション"
    },
    {
        id: 9,
        title: "緑のテラスハウス",
        price: 98000,
        type: "テラスハウス",
        location: "東京都目黒区自由が丘",
        rooms: "2DK",
        size: 45.0,
        station: "自由が丘駅",
        walkTime: 11,
        image: "/api/placeholder/400/300",
        features: ["専用庭付", "角部屋", "リノベーション"],
        description: "自由が丘の閑静な住宅街、庭付きテラスハウス"
    },
    {
        id: 10,
        title: "モダンアーバンレジデンス",
        price: 88000,
        type: "マンション",
        location: "東京都文京区本郷",
        rooms: "1DK",
        size: 30.0,
        station: "本郷三丁目駅",
        walkTime: 4,
        image: "/api/placeholder/400/300",
        features: ["デザイナーズ", "オートロック", "宅配ボックス"],
        description: "文教地区の利便性の高い好立地物件"
    }
];

export default properties;
